version: "3.7"
services:
  yat:
    image: node:8.14
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
    volumes:
       - .:/app
       - node_modules:/app/node_modules/
volumes:
  node_modules:
