version: "3.7"
services:
  server:
    build:
      context: ./server
      target: BASE
    working_dir: /app
    command: bash -c "realize start"
    environment:
      - GOPATH=/app
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
  client:
    image: node:8.14
    working_dir: /app
    command: bash -c "yarn install && yarn start"
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
    volumes:
       - ./client:/app
       - node_modules:/app/node_modules/
volumes:
  node_modules:
